---
http_interactions:
- request:
    method: get
    uri: http://127.0.0.1:19090/api/v1/query?query=node_systemd_unit_state%7Bname='not_running.service',state='active'%7D
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Mon, 24 Apr 2017 13:30:10 GMT
      Content-Length:
      - '239'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"node_systemd_unit_state","instance":"node-exporter1:9100","job":"prometheus","name":"not_running.service","state":"active"},"value":[1493040610.959,"0"]}]}}'
    http_version: 
  recorded_at: Mon, 24 Apr 2017 13:30:10 GMT
recorded_with: VCR 3.0.3
